# Generated by Django 3.0.3 on 2020-05-18 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameStatus', models.IntegerField(choices=[(0, 'waiting'), (1, 'ongame'), (2, 'finished'), (3, 'cancelled')], null=True)),
                ('winner', models.IntegerField(choices=[(0, 'player1'), (1, 'player2')], null=True)),
                ('firstPlayer', models.IntegerField(choices=[(0, 'player1'), (1, 'player2')], null=True)),
                ('lastUpdated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField(choices=[(0, 'player1'), (1, 'player2')])),
                ('turn', models.IntegerField()),
                ('isPass', models.BooleanField()),
                ('isSurrender', models.BooleanField()),
                ('posX', models.IntegerField()),
                ('posY', models.IntegerField()),
                ('board', models.CharField(max_length=64)),
                ('flips', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_game', to='othello.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_player1', to='othello.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_player2', to='othello.Player'),
        ),
    ]
