# Generated by Django 3.0.3 on 2020-05-23 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('othello', '0002_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameStatus',
            new_name='status',
        ),
    ]
