# Generated by Django 3.0.3 on 2020-05-24 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('othello', '0004_auto_20200523_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_player', to='othello.Player'),
        ),
    ]
